# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            DayTah
tagline:          'All things data, design & dev related'
description:      'Notes & reflections on daily readings: data, design & dev'
url:              'http://vinodxyz.github.io/blog'
baseurl:          '/blog/'
#
#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

## Custom vars
#version:          2.1.0
#
#github:
#  repo:           https://github.com/poole/hyde
